import React, { useEffect, useState } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import BallotGroup from '../components/BallotGroup'

const Home: NextPage = () => {
  const [ballotGroup, setBallotGroup] = useState<IBallotGroup[]>([]);

  useEffect(() => {
    fetch('http://localhost:3000/api/ballots')
      .then(res => res.json())
      .then(data => {
        setBallotGroup(data.items);
      });
  }, []);

  console.log(ballotGroup);

  return (
    <div className={styles.container}>
      <Head>
        <title>Take Home Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          AWARDS 2021
        </h1>
        {ballotGroup.length > 0 && ballotGroup.map((ballot: IBallotGroup, index: number) => (
          <BallotGroup key={ballot.id} {...ballot} />
        ))}
      </main>
    </div>
  )
}

export default Home
